kind = "api"
previewPath = "/"
title = "India Runs AI — Sandbox"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Sandbox UI"
paths = ["/"]

[services.env]
PORT = "8080"

[services.development]
run = "streamlit run ../../app.py --server.address 0.0.0.0 --server.headless true --server.enableCORS=false --server.enableXsrfProtection=false --server.port 8080"

[services.production.run]
args = [
  "streamlit",
  "run",
  "app.py",
  "--server.address",
  "0.0.0.0",
  "--server.headless",
  "true",
  "--server.enableCORS=false",
  "--server.enableXsrfProtection=false",
  "--server.enableWebsocketCompression=false",
  "--server.port",
  "8080",
]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/"
